### ISSUE TITLE
upgrading to 1.1.3 , causing  nasty erro - happens after a click of a submit button

### ISSUE THREAD

**Issue by yohannesalazar** [Cognifide/bobcat#140]
I tried upgrading to bobcat 1.1.3 and i get this nasty error on some of my scenarios :

 I try debugging but seems to be too hard to know where it is coming from ??? and am sorry but am not able to provide a step by step how to reproduce, as it happens only on one of my submit buttons only .

java.lang.StackOverflowError
    at java.util.HashMap.hash(HashMap.java:338)
    at java.util.LinkedHashMap.get(LinkedHashMap.java:440)
    at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:77)
    at com.sun.proxy.$Proxy47.value(Unknown Source)
    at sun.reflect.annotation.AnnotationSupport.getIndirectlyPresent(AnnotationSupport.java:103)
    at sun.reflect.annotation.AnnotationSupport.getDirectlyAndIndirectlyPresent(AnnotationSupport.java:72)
    at java.lang.reflect.Field.getAnnotationsByType(Field.java:1132)
    at com.cognifide.qa.bb.loadable.hierarchy.util.LoadableComponentsUtil.getConditionsFormField(LoadableComponentsUtil.java:39)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:116)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.processLoadableContextForClass(ConditionsExplorer.java:114)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.lambda$processLoadableContextForClass$3(ConditionsExplorer.java:117)
    at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer$$Lambda$32/109175108.accept(Unknown Source)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(

**Comment by mmanski** [comment]
Could you provide code snippets of your Steps class and page object with the web element which is causing this error?
