### ISSUE TITLE
NullPointerException in ConditionExplorer.class

### ISSUE THREAD

**Issue by F3Ni0** [Cognifide/bobcat#141]
Hi

I have created a class which performs log in on page.

My Login Class snippet
```
@PageObject
public class LoginPage {
	
	@Inject
	private WebDriver driver;
	
	@FindBy(css = "input[class='un']")
	private WebElement loginTextField;

	public LoginPage sendLogin(String login) {
		loginTextField.clear();
		loginTextField.sendKeys(login);
		return this;
	}
```

I use BDD AEM archetype, so i `@Inject private LoginPage loginPage;` to my Steps class.
When I run the test i have a `NullPointerException`.

Full stack trace:
```
16:30:37.145 [main] DEBUG com.cognifide.qa.bb.loadable.hierarchy.WebElementInterceptor - Caught invocation of method clear from pl.ttms.pageobjects.affiliate.generic.LoginPage. Started processing loadable component conditions hierarchy
java.lang.NullPointerException
at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.findNode(ConditionsExplorer.java:146)
	at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.discoverLoadableContextHierarchy(ConditionsExplorer.java:73)
	at com.cognifide.qa.bb.loadable.hierarchy.WebElementInterceptor.invoke(WebElementInterceptor.java:65)
	at pl.ttms.pageobjects.affiliate.generic.LoginPage.sendLogin(LoginPage.java:38)
	at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
	at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
	at pl.ttms.pageobjects.affiliate.generic.LoginPage.logIn(LoginPage.java:55)
	at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
	at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
	at pl.ttms.steps.affiliate.ItalyHomePageSteps.i_log_in_as_italy_user(ItalyHomePageSteps.java:75)
	at com.cognifide.qa.bb.assertions.soft.SoftAssertionsAspect.invoke(SoftAssertionsAspect.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
	at cucumber.runtime.Runtime.runStep(Runtime.java:299)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

I can answer questions, provide more code etc.
I thought it should work, but either I am doing something wrong, or there is a bug.

**Comment by kkarolk** [comment]
Hi,
thank you for submitting an issue, we will try to reproduce that.

**Comment by mmanski** [comment]
Hi, could you please provide version of Bobcat that you are using? Also, please attach your Steps class and your test runner with class imports. Imports of the class you have already attached would be also helpful as well as web driver type and it's version.

**Comment by F3Ni0** [comment]
I was trying to isolate NPE throwing code, but I was unable to reproduce this issue.
Thank you for your support.
