### ISSUE TITLE
NullPointerException in ConditionsExplorer.java:139

### ISSUE THREAD

**Issue by kkarolk** [Cognifide/bobcat#155]
Consider following code setup:

Hook:
`@Before({"@setup", "@myStore"})
	public void tearDown() {
		homePage.open();
		homePage.getLoginBox().enterLogin("my login");
}`

HomePage:

`
@PageObject
public class HomePage extends PublishPage {

	@FindBy(css = ".login")
	private LoginBox loginBox;

	public LoginBox getLoginBox() {
		return loginBox;
	}
}
`

LoginBox:

`@PageObject
public class LoginBox {

	@FindBy(css = "input[name=username]")
	private WebElement usernameInput;

	public LoginBox enterLogin(String login) {
		usernameInput.sendKeys(login);
		return this;
	}
}
`

When running hook before cucumber scenario, following exception in thrown:

`java.lang.NullPointerException
	at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.findNode(ConditionsExplorer.java:139)
	at com.cognifide.qa.bb.loadable.hierarchy.ConditionsExplorer.discoverLoadableContextHierarchy(ConditionsExplorer.java:78)
	at com.cognifide.qa.bb.loadable.hierarchy.WebElementInterceptor.invoke(WebElementInterceptor.java:70)
	at com.cognifide.douglasclub.pageobjects.login.LoginBox.enterLogin(LoginBox.java:24)
	at com.cognifide.qa.bb.loadable.hierarchy.PageObjectInterceptor.invoke(PageObjectInterceptor.java:42)
	at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
	at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
	at com.cognifide.douglasclub.hooks.MyStoreHooks.tearDown(MyStoreHooks.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)`

**Comment by Shaihuludus** [comment]
Fixed and released
