### ISSUE TITLE
 passing parameters (works on  webdriver.properties) does not always work on terminal

### ISSUE THREAD

**Issue by yohannesalazar** [Cognifide/bobcat#165]
webdriver.properties files as below

webdriver.type=appium
webdriver.appium.url=http://ASAS:YSSSSSSXEy12Z4K@hub-cloud.browserstack.com/wd/hub
webdriver.cap.platformName=iOS
webdriver.cap.deviceName=iPhone 6
webdriver.cap.browserName=iPad
webdriver.cap.platformVersion=9.1
webdriver.mobile=true
webdriver.reusable=true
webdriver.maximize=false
webdriver.cap.device=iPad Air 2
browserstack.debug=true
webdriver.cap.autoAcceptAlerts=true

above works fine, but if commented out the above and I do exact same parameters on terminal mvn as below
mvn clean test -Dcucumber.options="--tags @mobile" -Dwebdriver.type="appium" -Dwebdriver.appium.url="http://ASAS:YSSSSSSXEy12Z4K@hub-cloud.browserstack.com/wd/hub" -Dwebdriver.cap.platformName="iOS" -Dwebdriver.cap.browserName="iPad" -Dwebdriver.mobile="true" -Dwebdriver.reusable="true" -Dwebdriver.maximize="false" -Dwebdriver.cap.device="iPad Air 2" -Dbrowserstack.debug="true" -Dwebdriver.cap.autoAcceptAlerts="true"

com.google.inject.ProvisionException: Guice provision errors:

1) Error in custom provider, java.lang.IllegalArgumentException: java.net.MalformedURLException
  while locating com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider
  while locating org.openqa.selenium.WebDriver
    for field at com.rx.automation.hooks.WindowMaximize.webDriver(WindowMaximize.java:11)
  while locating com.rx.automation.hooks.WindowMaximize
Caused by: java.lang.IllegalArgumentException: java.net.MalformedURLException
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverType$8.createMobileDriver(WebDriverType.java:109)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverType$8.create(WebDriverType.java:101)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider.create(WebDriverProvider.java:107)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider.get(WebDriverProvider.java:98)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider.get(WebDriverProvider.java:48)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at cucumber.runtime.java.guice.impl.GuiceFactory.getInstance(GuiceFactory.java:45)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
        at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
        at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
        at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.MalformedURLException
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverType$8.createMobileDriver(WebDriverType.java:107)
        ... 44 more
Caused by: java.lang.NullPointerException
        at java.net.URL.<init>(URL.java:532)
        ... 47 more

2) Error in custom provider, java.lang.IllegalArgumentException: java.net.MalformedURLException
  while locating com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider
  while locating org.openqa.selenium.WebDriver
    for field at com.rx.automation.pageobjects.UtilWebdriver.webDriver(UtilWebdriver.java:17)
  while locating com.rx.automation.pageobjects.UtilWebdriver
    for field at com.rx.automation.hooks.WindowMaximize.utilWebdriver(WindowMaximize.java:11)
  while locating com.rx.automation.hooks.WindowMaximize
Caused by: java.lang.IllegalArgumentException: java.net.MalformedURLException
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverType$8.createMobileDriver(WebDriverType.java:109)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverType$8.create(WebDriverType.java:101)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider.create(WebDriverProvider.java:107)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider.get(WebDriverProvider.java:98)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverProvider.get(WebDriverProvider.java:48)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at cucumber.runtime.java.guice.impl.GuiceFactory.getInstance(GuiceFactory.java:45)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
        at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
        at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
        at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.MalformedURLException
        at java.net.URL.<init>(URL.java:627)
        at java.net.URL.<init>(URL.java:490)
        at java.net.URL.<init>(URL.java:439)
        at com.cognifide.qa.bb.provider.selenium.webdriver.WebDriverType$8.createMobileDriver(WebDriverType.java:107)
        ... 48 more
Caused by: java.lang.NullPointerException
        at java.net.URL.<init>(URL.java:532)
        ... 51 more

2 errors
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at cucumber.runtime.java.guice.impl.GuiceFactory.getInstance(GuiceFactory.java:45)
        at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
        at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:223)
        at cucumber.runtime.Runtime.runHooks(Runtime.java:211)
        at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:201)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Tests run: 10, Failures: 0, Errors: 7, Skipped: 3, Time elapsed: 3.675 sec <<< FAILURE! - in com.rx.automation.RunSiteVisitorTest
Scenario: Exhibitors page  Time elapsed: 0.484 sec  <<< ERROR!
com.google.inject.ProvisionException: Guice provision errors:

**Comment by mkrzyzanowski** [comment]
Hi, @yohannesalazar!

Unfortunately, due to the way we bind properties, you have to leave the properties file in place to be able to override them via command line. You can leave them empty, they just need to be there so Bobcat can load them in the first place.

I've raised #166 to address it on our end.

**Comment by yohannesalazar** [comment]
Thanks for clarification
