### ISSUE TITLE
Reporter Module uses bean provided by Aem Classic Module

### ISSUE THREAD

**Issue by mmanski** [Cognifide/bobcat#181]
When using Reporter Module there is a need to install Aem Classic Module despite the fact that it is not used explicitly. The problem is that Classic Module provides CloseableHttpClient which is used by Reporter Module. It should be refactored so the HttpClient will be provided by bb core, reporter module or aem common

**Comment by mmanski** [comment]
Stacktrace:
`com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.apache.http.impl.client.CloseableHttpClient was bound.
  while locating org.apache.http.impl.client.CloseableHttpClient
    for field at com.cognifide.qa.bb.aem.AemAuthCookieFactory.httpClient(AemAuthCookieFactory.java:51)
  while locating com.cognifide.qa.bb.aem.AemAuthCookieFactory
    for field at com.cognifide.qa.bb.aem.AemLogin.aemAuthCookieFactory(AemLogin.java:31)
  while locating com.cognifide.qa.bb.aem.AemLogin
    for field at com.cp.colgate.aem.bobcat.zg.permissions.AuthorPermissionsTest.aemLogin(AuthorPermissionsTest.java:31)
  while locating com.cp.colgate.aem.bobcat.zg.permissions.AuthorPermissionsTest

1 error

	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at com.cognifide.qa.bb.junit.TestRunner.createTest(TestRunner.java:97)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at com.cognifide.qa.bb.junit.TestRunner.runMethod(TestRunner.java:167)
	at com.cognifide.qa.bb.junit.TestRunner.runChild(TestRunner.java:127)
	at com.cognifide.qa.bb.junit.TestRunner.runChild(TestRunner.java:61)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.cognifide.qa.bb.junit.TestRunner.run(TestRunner.java:140)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`

**Comment by mkrzyzanowski** [comment]
From now on, using CloseableHttpClient will require installing `AemCommonModule`
