### ISSUE TITLE
HELP: how to access a particular parsys in a page.

### ISSUE THREAD

**Issue by DeChrish** [Cognifide/bobcat#202]
We have created a page and dragged container component in the main parsys.
Now the page have 2 parsys because container has a parsys within. Now we need to edit container component which has data path as below.

**Child Parsys**: added by the below parsys: **/test/jcr:content/bodypar/container**
**Main Parsys**: used to add  the above container parsys **:  /test/jcr:content/bodypar/***

` page.configureComponent("/bodypar/container", COMPONENT_NAME, "container_demo");`

Log:
`
throws null point exceptions.
<java.lang.NullPointerException: null
	at com.cognifide.qa.bb.aem.touch.data.components.Components.getDataPath(Components.java:45)
	at com.cognifide.qa.bb.aem.touch.pageobjects.touchui.Parsys.getComponent(Parsys.java:104)
	at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
	at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
	at com.cognifide.qa.bb.aem.touch.pageobjects.touchui.Parsys.configureComponent(Parsys.java:157)
	at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
	at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
	at com.cognifide.qa.bb.aem.touch.pageobjects.pages.AuthorPage.configureComponent(AuthorPage.java:196)
	at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
	at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)>
`

**Comment by mkrzyzanowski** [comment]
Hi @DeChrish,

what version of AEM are you working with?

The `NullPointerException` in the log you sent suggests that description of your component is missing from 'component-descriptions.yaml' (documentation [here](https://github.com/Cognifide/bobcat/wiki/Component-descriptions) ), namely in your case something like:
```
...
COMPONENT_NAME:
    datapath: /container
    clazz: <page-object-of-your-component>
...
```

Please note that the container components were not extensively used and tested with current TouchUI module - let us know if the above helps.

**Comment by DeChrish** [comment]
Hi @mkrzyzanowski i will try and get the feedback.

**Comment by mkrzyzanowski** [comment]
Closing this for now, if you have any update, please let us know.

**Comment by discovermoi** [comment]
Hi @DeChrish, I need help in using the configureComponent function. I am consistently facing YAML could not be read. https://github.com/Cognifide/bobcat/issues/241.

I am trying to configure a simple component with dialog fields supported by the framework. I am not able to identify what kind of mistake that I am doing.
