### ISSUE TITLE
selenium version?

### ISSUE THREAD

**Issue by warn4n** [Cognifide/bobcat#204]
Getting this,

`1 error
  POST /session/0215473d-4ea5-e146-8165-55610d4d7ffd/log did not match a known command
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
`

And I see there is an open issue to support selenium 3.4.0, so I surmise I might need to downgrade my selenium. I didn't see any documentation of what the expected version of selenium is though?

thanks,

Warren

**Comment by warn4n** [comment]
Hmmm.. looks like it is 3.4.0 https://github.com/Cognifide/bobcat/blob/1.2.1/pom.xml so that's probably not my problem

**Comment by warn4n** [comment]
or maybe this is closer to the root cause?

`1 error
  Guice configuration errors:

1) No implementation for org.apache.http.impl.client.CloseableHttpClient was bound.
  while locating org.apache.http.impl.client.CloseableHttpClient
    for field at com.cognifide.qa.bb.aem.AemAuthCookieFactory.httpClient(AemAuthCookieFactory.java:51)
  while locating com.cognifide.qa.bb.aem.AemAuthCookieFactory
    for field at com.cognifide.qa.bb.aem.AemLogin.aemAuthCookieFactory(AemLogin.java:31)
  while locating com.cognifide.qa.bb.aem.AemLogin
`
