### ISSUE TITLE
Bobcat & Firefox - NoSuchMethodError

### ISSUE THREAD

**Issue by jplucinski** [Cognifide/bobcat#205]
# Problem
Tested web page opens successfully, but gives en exception:
```
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.WebDriverWait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
at com.cognifide.qa.bb.provider.selenium.BobcatWebDriverWait.until(BobcatWebDriverWait.java:70)
  at com.ford.guxfoe.pageobjects.components.buildandprice.BuildAndPriceLoaderComponent.waitUntilDisappears(BuildAndPriceLoaderComponent.java:23)
  at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
  at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
  at com.ford.guxfoe.pageobjects.components.buildandprice.BuildAndPricePage.open(BuildAndPricePage.java:124)
  at com.ford.guxfoe.pageobjects.components.buildandprice.BuildAndPricePage.openMockBsl(BuildAndPricePage.java:70)
  at com.cognifide.qa.bb.frame.FrameAspect.switchFrameAndProceed(FrameAspect.java:70)
  at com.cognifide.qa.bb.frame.FrameAspect.invoke(FrameAspect.java:58)
```

# Setup
Bobcat 1.1.3
Firefox: 54.0.1
Gecko driver 0.17.0

# Configuration
webdriver.properties
> webdriver.type=firefox
> webdriver.gecko.driver=C:/geckodriver.exe

Apply workaround from https://github.com/Cognifide/bobcat/issues/198
> 		<dependency>
> 			<groupId>com.google.guava</groupId>
> 			<artifactId>guava</artifactId>
> 			<version>21.0</version>
> 		</dependency>

Added Selenium server:
> 		<dependency>
> 			<groupId>org.seleniumhq.selenium</groupId>
> 			<artifactId>selenium-server</artifactId>
> 			<version>3.4.0</version>
> 		</dependency>

**Comment by mkrzyzanowski** [comment]
Related to #198. Closing.
