### ISSUE TITLE
NullPointerException for @StoreFailedResults

### ISSUE THREAD

**Issue by F3Ni0** [Cognifide/bobcat#213]
Hi!

My Runner which should produce failed results:
```
@RunWith(Bobcumber.class)
@StoreFailedResults("target/failedTests.properties")
@CucumberOptions(
    plugin = {"pretty", "html:target/cucumber-html-report/automation/failing-test/",
        "json:target/failing+test.json",
        "junit:target/junit-report/failing-test.xml"},
    tags = {"@failing"},
    glue = "com.java", //Step definition
    monochrome = true
)
public class FailingTest {

}
```

results in NPE:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.387 sec <<< FAILURE! - in runners.rerunner.FailingTest
initializationError(runners.rerunner.FailingTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:277)
	at com.cognifide.qa.bb.cumber.Bobcumber.createFile(Bobcumber.java:105)
	at com.cognifide.qa.bb.cumber.Bobcumber.<init>(Bobcumber.java:86)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by mkrzyzanowski** [comment]
We're removing the re-run feature 😺. The rationale is that we highly recommend reviewing and addressing the failing tests instead of simply rerunning them.
