### ISSUE TITLE
Couldn't run Bobcat AEM BDD Gradle Template project

### ISSUE THREAD

**Issue by aravindanck** [Cognifide/bobcat#267]
## Environment

Bobcat version: 1.4.0/1.3.0

Bobcat modules used:

* bb-aem-classic
* bb-aem-touch-ui

## Expected Behavior
Opens AEM login URL on browser, sends uname/pwd and logs in

## Actual Behavior
Exception thrown

## Steps to reproduce
I'm trying to test the [Bobcat AEM BDD gradle template](https://github.com/Cognifide/bobcat-gradle-template), which has a login feature defined to test author login in AEM. 
AEM server version: 6.2
When I test it, the following exception is thrown:

Exception in thread "main" cucumber.runtime.CucumberException: Failed to instantiate public cucumber.runtime.java.JavaBackend(cucumber.runtime.io.ResourceLoader) with [cucumber.runtime.io.MultiLoader@4b41e4dd]
	at cucumber.runtime.Reflections.newInstance(Reflections.java:44)
	at cucumber.runtime.Reflections.instantiateSubclasses(Reflections.java:30)
	at cucumber.runtime.Runtime.loadBackends(Runtime.java:98)
	at cucumber.runtime.Runtime.<init>(Runtime.java:65)
	at cucumber.api.cli.Main.run(Main.java:35)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.Reflections.newInstance(Reflections.java:41)
	... 5 more
Caused by: cucumber.runtime.CucumberException: Failed to instantiate public cucumber.runtime.java.guice.impl.GuiceFactory() throws java.io.IOException with []
	at cucumber.runtime.Reflections.newInstance(Reflections.java:44)
	at cucumber.runtime.Reflections.instantiateSubclasses(Reflections.java:30)
	at cucumber.runtime.Reflections.instantiateExactlyOneSubclass(Reflections.java:16)
	at cucumber.runtime.java.ObjectFactoryLoader.loadObjectFactory(ObjectFactoryLoader.java:28)
	at cucumber.runtime.java.JavaBackend.<init>(JavaBackend.java:65)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.Reflections.newInstance(Reflections.java:41)
	... 14 more
Caused by: com.google.inject.CreationException: Guice creation errors:

1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=author.ip) was bound.
  at com.cognifide.qa.bb.aem.AemCommonModule.getAuthorHttpClient(AemCommonModule.java:74)

2) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=author.login) was bound.
  at com.cognifide.qa.bb.aem.AemCommonModule.getAuthorHttpClient(AemCommonModule.java:74)

3) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=author.password) was bound.
  at com.cognifide.qa.bb.aem.AemCommonModule.getAuthorHttpClient(AemCommonModule.java:74)

4) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=author.ip) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=author.ip)
    for field at com.cognifide.qa.bb.provider.jcr.properties.AuthorProperties.authorIp(AuthorProperties.java:31)
  at com.cognifide.qa.bb.aem.AemCommonModule.configure(AemCommonModule.java:48)

5) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=author.login) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=author.login)
    for field at com.cognifide.qa.bb.provider.jcr.properties.AuthorProperties.authorLogin(AuthorProperties.java:31)
  at com.cognifide.qa.bb.aem.AemCommonModule.configure(AemCommonModule.java:48)

6) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=author.password) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=author.password)
    for field at com.cognifide.qa.bb.provider.jcr.properties.AuthorProperties.authorPassword(AuthorProperties.java:31)
  at com.cognifide.qa.bb.aem.AemCommonModule.configure(AemCommonModule.java:48)

7) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=publish.ip) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=publish.ip)
    for field at com.cognifide.qa.bb.provider.jcr.properties.PublishProperties.publishIp(PublishProperties.java:31)
  at com.cognifide.qa.bb.aem.AemCommonModule.configure(AemCommonModule.java:46)

8) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=publish.login) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=publish.login)
    for field at com.cognifide.qa.bb.provider.jcr.properties.PublishProperties.publishLogin(PublishProperties.java:31)
  at com.cognifide.qa.bb.aem.AemCommonModule.configure(AemCommonModule.java:46)

9) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=publish.password) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=publish.password)
    for field at com.cognifide.qa.bb.provider.jcr.properties.PublishProperties.publishPassword(PublishProperties.java:31)
  at com.cognifide.qa.bb.aem.AemCommonModule.configure(AemCommonModule.java:46)

9 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.sirius.bdd.aem.CucumberInjectorSource.getInjector(CucumberInjectorSource.java:13)
	at cucumber.runtime.java.guice.impl.GuiceFactory.<init>(GuiceFactory.java:22)
	... 19 more

**Comment by mkrzyzanowski** [comment]
The mentioned modules are not supported anymore, please let us know if the issue persists with new modules :).
